[package]
name = "baba-ze-ata"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-init = "2.0.1"
bevy = "0.8.1"
grid = "0.8.1"
no-panic = "0.1.15"
